[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "php81Extensions.mysqli", "php81Extensions.mbstring", "php81Extensions.intl", "php81Extensions.gd", "php81Extensions.curl", "apacheHttpd"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "apache2 -D FOREGROUND"
